[package]
name = "yt_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube = { version = "0.6.0", features = ["blocking"] }
druid = "0.8.3"
indicatif = "0.17.3"